version: '3'

services:
  app:
    container_name: fastapi_ocr
    build: .
    volumes:
      - ./server:/var/www/html
    ports:
      - "9004:9004"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004